---

environment_name: prd-ml-fon
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"

#from Datadog role variables
dd_enabled: yes
datadog_installed: True
dd_process_agent_enabled: True
dd_key: "{{ vault_dd_key }}"

#Backups
backup_server_host: a-v-bk-pp-001.dndc.intranet
backup_allowed_subnet: 10.250.29.0/24
backup_server_folder: /u01
backup_client_folder: /mnt/backups
backup_schedule: "@daily"
backup_keep_days: 3
backup_keep_weeks: 4
backup_keep_months: 1

#Host Timezone 
timezone: Africa/Bamako

etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'dndc.intranet'

dns_server_list:
  - 10.250.29.3
  - 10.250.29.4
  - 8.8.8.8
  - 8.8.4.4

# Logstash in Filebeat configuration
logstash_ip_port: ""
