---

vault_docker_registry: sogema-docker.jfrog.io
vault_docker_user: jenkins_
vault_docker_pwd: 

vault_db_user: 
vault_db_pass: 

vault_edms_password: 

vault_mail_password: 

vault_keycloak_wf_realm_public_key: ""
vault_keycloak_api_client_secret: ""
