---

#Docker Installed version
docker_compose_version: 1.21.2
docker_ce_version: 18.06.3~ce~3-0~ubuntu

docker_registry: "{{ vault_docker_registry }}"
docker_user: "{{ vault_docker_user }}"
docker_pwd: "{{ vault_docker_pwd }}"
docker_email: "jenkins@sti.systems"
docker_log_driver: "journald"

#Docker Containers Deployed
pull_images: no

#Feature Flags
is_datadog_on_docker: True
is_swarm_mode_enabled: False
is_docker_prospector_enabled: False

#Alfresco Vars
edms_data_disk: /u01 #the mountpoint in the OS disk accorded with DND

edms_csrf_filter_origin: http://a-v-ec-fo-001.dndc.intranet
edms_csrf_filter_referer: http://a-v-ec-fo-001.dndc.intranet/.*

alfresco_host: alfresco
alfresco_port: 8080

alfresco_url: http://a-v-wt-fo-003.dndc.intranet:8380

solr_host: alfresco-solr6
solr_port: 8983

edms_user_first_name: "SITFI"
edms_user_last_name: "Admin"

edms_admin_user: "admin"
edms_admin_password: "{{ vault_edms_admin_password }}"

edms_user: "for-sitfi@dndc.intranet"
edms_user_role: "SiteManager"
edms_password: "{{ vault_edms_password }}"

edms_site_id: foncier
edms_site_title: Formation SITFI
edms_site_description: "Formation SITFI"
edms_alfresco_folder: foncierEdmsDocuments

edms_db_host: alfresco-db
edms_db_port: 5432
edms_db_pass: alfresco

alfresco_xms: 6g
alfresco_xmx: 12g

share_xms: 512m
share_xmx: 2g

solr_xms: 2g
solr_xmx: 4g


etc_save_hosts:
    - name: "{{ ansible_ssh_host }}"
      ip: 127.0.0.1

# /etc/resolv.conf values
dns_resolv_searchpath:
  - 'dndc.intranet'


dns_server_list:
  - 10.250.29.3
  - 10.250.29.4
  - 8.8.8.8
  - 8.8.4.4


#Docker logs filebeat vars
docker_log_path: "/var/lib/docker/containers/*/*.log"
docker_conatiner_log_name: "fon"

#System logs filebeat vars:
system_log_path: "/var/log/*.log"
