---

full_hostname: A-V-WT-PR-007.dndc.intranet

# Feature flags - stuff we want to be present
jenkins_slave_node: False
node_installed: False #we build in the VM too
is_maven_server: False
is_sonar_enabled: False

available_docker_services:
  - foncier-wf
  - datadog
